export default [
    {
        id: 1,
        name: "器物的象徵: 佛教打造的中國物質世界",
        arthur: "柯嘉豪",
        type: "歷史書籍",
        publing: "遠足文化事業股份有限公司",
        publingDate: '2020/12/23',
        price: 520,
        quantity: 10,
        img: '../product-img/book2.png',
    },
    {
        id: 2,
        name: "跟著大衛．哈維讀資本論",
        arthur: "大衞．哈維",
        type: "當代思潮",
        publing: "漫遊者文化事業股份有限公司",
        publingDate: '2019/02/14',
        price: 420,
        quantity: 15,
        img: '../product-img/book1.png',
    },
    {
        id: 3,
        name: "埃及五千年：文明起源與王朝興衰的故事",
        arthur: "喬安．佛列契",
        type: "歷史書籍",
        publing: "日出出版文化事業股份有限公司",
        publingDate: '2020 / 12 / 29',
        price: 750,
        quantity: 6,
        img: '../product-img/book4.png',
    }, {
        id: 4,
        name: "征服的時代：從亞歷山大到哈德良的希臘世界",
        arthur: "安傑羅．查尼歐提斯",
        type: "歷史書籍",
        publing: "馬可孛羅文化事業股份有限公司",
        publingDate: '2021 / 01 / 07',
        price: 800,
        quantity: 8,
        img: '../product-img/book3.png',
    }, {
        id: 5,
        name: "從臺車到巴士：百年臺灣地方交通演進史",
        arthur: "陳家豪",
        type: "歷史書籍",
        publing: "左岸文化事業股份有限公司",
        publingDate: '2020 / 12 / 02',
        price: 450,
        quantity: 10,
        img: '../product-img/book6.png',
    }, {
        id: 6,
        name: "恐懼與自由: 透過二十五位人物的故事, 了解二次大戰如何改變人類的未來",
        arthur: "齊斯．洛韋",
        type: "歷史書籍",
        publing: "馬可孛羅文化事業股份有限公司",
        publingDate: '2021 / 03 / 06',
        price: 680,
        quantity: 12,
        img: '../product-img/book7.png',
    }, {
        id: 7,
        name: "被隱藏的帝國:一部發生於美國之外,被忽略的美國史",
        arthur: "丹尼爾．因莫瓦爾",
        type: "歷史書籍",
        publing: "臉譜出版社",
        publingDate: '2021 / 03 / 11',
        price: 680,
        quantity: 10,
        img: '../product-img/book9.png',
    }, {
        id: 8,
        name: "斯多葛主義生活: 如何避開焦慮、悲傷、失望、憤怒和不滿的情緒指南",
        arthur: "約翰．賽勒斯",
        type: "歷史書籍",
        publing: "晨星出版有限公司",
        publingDate: '2020 / 11 / 12',
        price: 290,
        quantity: 13,
        img: '../product-img/book10.png',
    }, {
        id: 9,
        name: "操控與反操控:德國法律人都在使用的日常修辭邏輯與謬誤偵知法",
        arthur: "賈誠柯",
        type: "歷史書籍",
        publing: "遠流出版事業股份有限公司",
        publingDate: '2021 / 01 / 27',
        price: 380,
        quantity: 10,
        img: '../product-img/book11.png',
    }, {
        id: 10,
        name: "哲學與宗教全史:人類三千年的思考之旅",
        arthur: "出口治明",
        type: "歷史書籍",
        publing: "究竟出版社股份有限公司",
        publingDate: '2020 / 10 / 01',
        price: 430,
        quantity: 4,
        img: '../product-img/book12.png',
    }, {
        id: 11,
        name: "懲罰的三大思辨: 懲罰是什麼? 為何要懲罰? 懲罰的是誰?",
        arthur: "迪迪耶．法尚",
        type: "歷史書籍",
        publing: "聯經出版事業股份有限公司",
        publingDate: '2019 / 11 / 01',
        price: 380,
        quantity: 7,
        img: '../product-img/book13.png',
    }, {
        id: 12,
        name: "精神分析引論",
        arthur: "西格蒙德．佛洛伊德",
        type: "歷史書籍",
        publing: "左岸文化事業股份有限公司",
        publingDate: '22018/11/28',
        price: 500,
        quantity: 9,
        img: '../product-img/book13.png',
    }
]